import { ExtendedTypographyOptions } from '@/types'

import { FONT_FAMILY, FontWeight } from './constants'
import { toRem } from './helpers'

export const typography: ExtendedTypographyOptions = {
  htmlFontSize: 16,

  fontFamily: FONT_FAMILY,
  fontSize: 14,

  fontWeightLight: FontWeight.Light,
  fontWeightRegular: FontWeight.Regular,
  fontWeightMedium: FontWeight.Medium,
  fontWeightBold: FontWeight.Bold,

  h1: {
    fontWeight: FontWeight.Bold,
    fontSize: toRem(96),
    lineHeight: 1,
  },
  h2: {
    fontWeight: FontWeight.Bold,
    fontSize: toRem(64),
    lineHeight: toRem(70),
  },
  h3: {
    fontWeight: FontWeight.Bold,
    fontSize: toRem(48),
    lineHeight: toRem(56),
  },
  h4: {
    fontWeight: FontWeight.Bold,
    fontSize: toRem(32),
    lineHeight: toRem(40),
  },
  h5: {
    fontWeight: FontWeight.Bold,
    fontSize: toRem(24),
    lineHeight: toRem(30),
  },
  h6: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Bold,
    fontSize: toRem(20),
    lineHeight: toRem(24),
    letterSpacing: 0,
  },
  subtitle1: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.SemiBold,
    fontSize: toRem(24),
    lineHeight: toRem(30),
    letterSpacing: 0,
  },
  subtitle2: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.SemiBold,
    fontSize: toRem(20),
    lineHeight: toRem(24),
    letterSpacing: 0,
  },
  subtitle3: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.SemiBold,
    fontSize: toRem(16),
    lineHeight: toRem(20),
    letterSpacing: 0,
  },
  subtitle4: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.SemiBold,
    fontSize: toRem(14),
    lineHeight: toRem(18),
    letterSpacing: 0,
  },
  subtitle5: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.SemiBold,
    fontSize: toRem(12),
    lineHeight: toRem(16),
    letterSpacing: 0,
  },
  body1: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Regular,
    fontSize: toRem(20),
    lineHeight: toRem(24),
    letterSpacing: toRem(0.4),
  },
  body2: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Regular,
    fontSize: toRem(16),
    lineHeight: toRem(20),
    letterSpacing: toRem(0.32),
  },
  body3: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Regular,
    fontSize: toRem(14),
    lineHeight: toRem(20),
    letterSpacing: toRem(0.28),
  },
  body4: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Regular,
    fontSize: toRem(12),
    lineHeight: toRem(16),
    letterSpacing: toRem(0.24),
  },
  button: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Medium,
    fontSize: toRem(14),
    lineHeight: toRem(18),
    letterSpacing: 0,
    textTransform: 'none',
  },
  buttonLarge: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Medium,
    fontSize: toRem(16),
    lineHeight: toRem(20),
  },
  buttonMedium: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Medium,
    fontSize: toRem(14),
    lineHeight: toRem(18),
    letterSpacing: 0,
  },
  buttonSmall: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Medium,
    fontSize: toRem(12),
    lineHeight: toRem(14),
    letterSpacing: 0,
  },
  caption1: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Medium,
    fontSize: toRem(14),
    lineHeight: toRem(18),
  },
  caption2: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Medium,
    fontSize: toRem(12),
    lineHeight: toRem(16),
  },
  caption3: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Medium,
    fontSize: toRem(10),
    lineHeight: toRem(12),
  },
  overline1: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Bold,
    fontSize: toRem(14),
    lineHeight: toRem(18),
    letterSpacing: toRem(0.56),
    textTransform: 'uppercase',
  },
  overline2: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Bold,
    fontSize: toRem(12),
    lineHeight: toRem(16),
    letterSpacing: toRem(0.48),
    textTransform: 'uppercase',
  },
  overline3: {
    fontFamily: FONT_FAMILY,
    fontWeight: FontWeight.Bold,
    fontSize: toRem(10),
    lineHeight: toRem(12),
    letterSpacing: toRem(0.4),
    textTransform: 'uppercase',
  },
}
